### ISSUE TITLE
texture.jpg has unclear license

### ISSUE THREAD

**Issue by hosiet** [linuxdeepin/blur-effect#1]
It seems that the `texture.jpg` file came from internet and has an unknown origin. There are many identical wallpaper images on the internet that can be found using image search. It is obvious that this image cannot be licensed under GPL-3.0+ and the copyright holder cannot be Deepin.

Please replace the image with an alternative that has certain copyright information and known copyright holder. Thanks.

**Comment by ClayStan** [comment]
Replaced with open source images in this commit :  https://github.com/linuxdeepin/blur-effect/commit/5a9e8e3b2c8f500fd89887f4a808673aed29faf1 , thanks.
